# Generated by Django 4.2.15 on 2024-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(max_length=15),
        ),
    ]
